### ISSUE TITLE
Reiser4 patch for latest linux 5.10.x kernels does not work

### ISSUE THREAD

**Issue by selkfoster** [edward6/reiser4#11]
Hello,

Matías Fonzo here, maintainer of Dragora GNU/Linux-Libre[1][2].

I just upgraded to linux version 5.10.100 applying the patch of reiser4 (5.10.2).  It gives the following build errors:

fs/reiser4/vfs_ops.o: warning: objtool: .text: unexpected end of section
  CC      fs/reiser4/as_ops.o
  CC      fs/reiser4/entd.o
  CC      fs/reiser4/readahead.o
  CC      fs/reiser4/status_flags.o
  CC      fs/reiser4/init_super.o
  CC      fs/reiser4/safe_link.o
  CC      fs/reiser4/blocknrlist.o
fs/reiser4/blocknrlist.c: In function ‘blocknr_list_sort_and_join’:
fs/reiser4/blocknrlist.c:211:25: error: passing argument 3 of ‘list_sort’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  211 |  list_sort(NULL, blist, blocknr_list_entry_compare);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                         |
      |                         int (*)(void *, struct list_head *, struct list_head *)
In file included from fs/reiser4/blocknrlist.c:15:
./include/linux/list_sort.h:13:68: note: expected ‘list_cmp_func_t’ {aka ‘int (*)(void *, const struct list_head *, const struct list_head *)’} but argument is of type ‘int (*)(void *, struct list_head *, struct list_head *)’
   13 | void list_sort(void *priv, struct list_head *head, list_cmp_func_t cmp);
      |                                                    ~~~~~~~~~~~~~~~~^~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:280: fs/reiser4/blocknrlist.o] Error 1
make[1]: *** [scripts/Makefile.build:497: fs/reiser4] Error 2
make: *** [Makefile:1826: fs] Error 2

[1] https://www.gnu.org/distros/free-distros.html
[2] https://www.dragora.org

**Comment by edward6** [comment]
Hello Matias,

Could you please also apply this patch from the ./fs/reiser4 directory:
https://github.com/edward6/reiser4/commit/de7c84bd06bf4044b9a052eaf6266322fa4aa02c

Let me know, if any problems.

Thanks,
Edward.

**Comment by selkfoster** [comment]
Hi @edward6 !

I just finished the compilation, there were no errors after applying the patch you said.

**Comment by selkfoster** [comment]
It would be nice if the patches can be published on the SourceForge link[1].

[1] https://sourceforge.net/projects/reiser4/files/

I am closing this issue.  Thanks for maintaining the ReiserFS!
