### ISSUE TITLE
Feature request - implement reiserfs as portable library

### ISSUE THREAD

**Issue by SergeyVolkovich99** [edward6/reiser4#9]
Hello.
Please excuse my impudence but i had one question about possibility refactoring code as portable library which may work through wrapper on any os.
Anyway thanks for any answer.

**Comment by edward6** [comment]
Dear Sergey,

Currently such library doesn't exist. Historically, all file systems of Reiser family were planned as native file systems for LInux.
Such refactoring is possible only in a context of a real task on porting Reiser4 to some other OS. I estimate the complexity of such a task as high. If interesting, I can forward you a mail thread (in Russian) with a person, who investigated a possibility to port Reiser4 to an OS of BSD family.

Thanks,
Edward.

**Comment by SergeyVolkovich99** [comment]
Ok, in how format you may do that.

**Comment by SergeyVolkovich99** [comment]
If what , i perfectly understand that language.

**Comment by edward6** [comment]
For this I need your email address..

**Comment by SergeyVolkovich99** [comment]
sergey.volkovich99@outlook.com
